"""big-file 提取器测试（#59）：五元组 + 候选线 + 排除口径 + 注入。"""

import json

from lib.big_file import (
    HOTSPOT_LINE,
    LINES_LINE,
    TOKEN_REFERENCE,
    big_file_payload,
)


def _make_repo(tmp_path):
    repo = tmp_path / "repo"
    repo.mkdir()
    (repo / "src").mkdir()
    # 巨石：4 字符/token × 32K token 参考线 → > 128_000 字符
    big = "x = 1\n" * 25_000  # 150_000 字符 → 37_500 token 估算
    (repo / "src" / "big.py").write_text(big, encoding="utf-8")
    # 普通
    (repo / "src" / "small.py").write_text("def f():\n    pass\n",
                                           encoding="utf-8")
    # 排除口径各一
    (repo / "vendor").mkdir()
    (repo / "vendor" / "vend.py").write_text(big, encoding="utf-8")
    (repo / "src" / "generated.py").write_text(
        "# @generated by tool\n" + big, encoding="utf-8")
    (repo / "package-lock.json").write_text("{}", encoding="utf-8")
    return repo, big


class TestFiveTuple:
    def test_five_tuple_fields(self, tmp_path):
        repo, big = _make_repo(tmp_path)
        payload = big_file_payload(repo)
        files = {f["file"]: f for f in payload["files"]}
        assert set(files) == {"src/big.py", "src/small.py"}  # vendor/generated/lockfile 排除（generated.py 带 @generated 头）

        f = files["src/big.py"]
        assert f["lines"] == 25_001  # 25_000 个换行 + 无换行末行
        assert f["bytes"] == len(big.encode())
        assert f["tokens_estimate"] == len(big) // 4
        assert f["symbols"] is None  # 无注入
        assert f["hotspot"] is None  # 无热点数据

    def test_generated_and_lockfile_excluded(self, tmp_path):
        repo, _ = _make_repo(tmp_path)
        payload = big_file_payload(repo)
        names = {f["file"] for f in payload["files"]}
        assert "src/generated.py" not in names  # @generated 标记排除
        assert "vendor/vend.py" not in names

    def test_candidates_by_token_reference(self, tmp_path):
        repo, _ = _make_repo(tmp_path)
        payload = big_file_payload(repo)
        assert payload["token_reference"] == TOKEN_REFERENCE
        assert payload["candidates"] == ["src/big.py"]  # 150K 字符 → 37500 token > 32K 参考线


class TestLinesLine:
    def test_by_lines_sample(self, tmp_path):
        """超 800 行文件另出 by_lines 采样（验收对照口径）。"""
        repo = tmp_path / "repo"
        repo.mkdir()
        (repo / "src").mkdir()
        (repo / "src" / "a.py").write_text("\n" * 900, encoding="utf-8")
        (repo / "src" / "b.py").write_text("\n" * 100, encoding="utf-8")
        payload = big_file_payload(repo)
        assert payload["lines_line"] == LINES_LINE
        assert payload["by_lines"] == ["src/a.py"]


class TestInjection:
    def test_symbol_and_hotspot_injection(self, tmp_path):
        repo, _ = _make_repo(tmp_path)
        payload = big_file_payload(
            repo,
            symbol_counts={"src/big.py": 42},
            hotspot_counts={"src/big.py": 10},
        )
        f = {x["file"]: x for x in payload["files"]}["src/big.py"]
        assert f["symbols"] == 42
        assert f["changes_90d"] == 10
        assert f["hotspot"] is True  # 10 ≥ HOTSPOT_LINE

        payload2 = big_file_payload(repo, hotspot_counts={"src/big.py": 2})
        f2 = {x["file"]: x for x in payload2["files"]}["src/big.py"]
        assert f2["hotspot"] is False  # 2 < HOTSPOT_LINE
        assert f2["symbols"] is None

    def test_deterministic(self, tmp_path):
        repo, _ = _make_repo(tmp_path)
        a = json.dumps(big_file_payload(repo), sort_keys=True)
        b = json.dumps(big_file_payload(repo), sort_keys=True)
        assert a == b
