"""big-file 提取器（#59 新写）：体量五元组 + 候选线，供 E 族 monolith-file 判罪。

判据权威来源：criteria/E-process.md §2——确定性档产「体量事实五元组」，
候选线 = token 估算超中位 agent 有效预算参考线（32K，判据原话「候选线
不是判罪线」）；「大不是罪，大且必须全读才是」，局部性判定归 LLM 档
（module_depth 协议复用，不在本提取器）。

票面口径：体量五元组 = 行数、字节数、符号数、token 估算、**修改局部性
标记位**。前四项确定可提取；第五项「修改局部性」判据原文归 LLM 档
（「修改局部性评估」），但票面把它列为五元组成员——落地裁决：确定性
侧放**代理标记位** `hotspot`（该文件 git 热点改动 ≥ 热线阈值，取自
hotspot.json 口径的 90 天窗口；LLM 局部性评估的 cheap 先行信号），
真正的局部性判定仍归 LLM 档。热点数据由调用方注入（`scan.py` 先跑
hotspot 再跑 big-file 的执行序保证）；无热点数据时该位为 null（未知）。

五元组细节：
- 行数：`text.count("\\n") + 1`（无尾换行的末行也计）；
- 字节数：文件字节长度；
- 符号数：symbols 工件口径的命名符号（tree-sitter 缺失时 null）；
- token 估算：字符 ≈ 4:1（判据原文「token 估算（字符 ≈ 4:1）」）；
- hotspot：90 天窗口改动次数 ≥ `_HOTSPOT_LINE`（8，open-vibe-island
  实测 top 文件量级校准）为 true。

排除口径：@generated / vendored / lockfile 与 duplicate-code 确定性档
同口径（判据原文）。vendored 目录复用 symbols 的排除集；@generated 扫
文件头注释标记；lockfile 按文件名通配。**注意**：test/tests 不排除
（债检测要扫测试，巨石测试文件同样是债）。

产物（big_file.json data 载荷）：
- `files`：**全部**源文件的五元组（不只候选——E 族 LLM 档与渲染器
  需要全集做中位数等统计）；
- `candidates`：token 估算超 32K 参考线的文件清单（候选线在载荷头
  `token_reference` 标注，供判据校准回看）。

对 open-vibe-island 实测：32K token ≈ 4 字符/token → ~128K 字符 ≈
3200 行级，BridgeServer.swift（3226 行）入候选；15 个超 800 行文件
的票面验收按行数线 800 在 `candidates` 之外另出 `by_lines` 采样
（验收对照口径）。
"""

from __future__ import annotations

from pathlib import Path

from lib.symbols import _EXCLUDE_DIR_TOKENS, file_language

# 32K token 参考线（E 族判据原文：中位 agent 有效预算参考线，候选线非判罪线）
TOKEN_REFERENCE = 32_000
_CHARS_PER_TOKEN = 4  # 判据原文：字符 ≈ 4:1

# 文件级排除（与 duplicate-code 确定性档同口径，判据原文）
_LOCKFILE_NAMES = frozenset({
    "package-lock.json", "yarn.lock", "pnpm-lock.yaml", "Gemfile.lock",
    "composer.lock", "Cargo.lock", "poetry.lock", "uv.lock", "go.sum",
})
_GENERATED_MARKERS = ("@generated", "DO NOT EDIT", "auto-generated",
                      "Generated by")

# 热线阈值：90 天窗口改动次数 ≥ 此值的文件带 hotspot 位（校准：样例仓
# top 热点文件 10-13 次，8 取「明显高于中位」的量级；阈值属候选线性质）
HOTSPOT_LINE = 8

# 验收对照口径：样例手工预筛的超 800 行文件（票面「约 15 个」）
LINES_LINE = 800


def _is_excluded(rel: Path, head: str) -> bool:
    """文件级排除：vendored/产物目录、lockfile、@generated 头标记。"""
    if any(part in _EXCLUDE_DIR_TOKENS for part in rel.parts):
        return True
    if rel.name in _LOCKFILE_NAMES:
        return True
    if any(m in head for m in _GENERATED_MARKERS):
        return True
    return False


def big_file_payload(repo: str | Path,
                     symbol_counts: dict[str, int] | None = None,
                     hotspot_counts: dict[str, int] | None = None) -> dict:
    """`big_file.json` 的 data 载荷（big-file 提取器产出）。

    Args:
        repo: 被扫仓库根。
        symbol_counts: 文件 → 符号数（来自 symbols 提取器，避免二次解析；
            None 时符号数记 null——五元组缺一角但不炸）。
        hotspot_counts: 文件 → 90 天改动次数（来自 hotspot 提取器；
            None 时 hotspot 位记 null=未知）。
    """
    root = Path(repo)
    symbol_counts = symbol_counts or {}
    hotspot_counts = hotspot_counts or {}

    files_out: list[dict] = []
    for p in sorted(root.rglob("*")):
        if not p.is_file():
            continue
        rel = p.relative_to(root)
        if any(part.startswith(".") for part in rel.parts):
            continue
        if file_language(rel) is None:
            continue  # 只统计可解析源码（与符号面同域）
        try:
            raw = p.read_bytes()
        except Exception:
            continue
        head = raw[:4096].decode("utf-8", errors="replace")
        if _is_excluded(rel, head):
            continue

        text = raw.decode("utf-8", errors="replace")
        lines = text.count("\n") + 1
        chars = len(text)
        rel_str = rel.as_posix()
        changes = hotspot_counts.get(rel_str)
        files_out.append({
            "file": rel_str,
            "lines": lines,
            "bytes": len(raw),
            "symbols": symbol_counts.get(rel_str),
            "tokens_estimate": chars // _CHARS_PER_TOKEN,
            "hotspot": (None if changes is None else changes >= HOTSPOT_LINE),
            "changes_90d": changes,
        })

    files_out.sort(key=lambda f: (-f["tokens_estimate"], f["file"]))
    candidates = [f for f in files_out
                  if f["tokens_estimate"] * _CHARS_PER_TOKEN
                  > TOKEN_REFERENCE * _CHARS_PER_TOKEN]
    by_lines = [f for f in files_out if f["lines"] > LINES_LINE]

    return {
        "token_reference": TOKEN_REFERENCE,
        "chars_per_token": _CHARS_PER_TOKEN,
        "hotspot_line": HOTSPOT_LINE,
        "lines_line": LINES_LINE,
        "files": files_out,
        "candidates": [f["file"] for f in candidates],
        "by_lines": [f["file"] for f in by_lines],
    }
